# Generated by Django 4.1.2 on 2022-12-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Rollno', models.BigIntegerField()),
                ('Course', models.CharField(max_length=20)),
                ('Phonenumber', models.BigIntegerField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=255)),
                ('MaritalStatus', models.CharField(max_length=15)),
                ('Weight', models.IntegerField()),
                ('Height', models.FloatField()),
                ('Gender', models.CharField(max_length=10)),
                ('PatientProblem', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('EntryTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Rollno', models.BigIntegerField()),
                ('Course', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=6)),
                ('Department', models.CharField(max_length=10)),
                ('Phonenumber', models.BigIntegerField()),
                ('Game', models.CharField(max_length=15)),
                ('Entry', models.CharField(max_length=6)),
                ('EntryTime', models.DateTimeField(auto_now_add=True)),
                ('ExitTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
